In [1]:
from sklearn.datasets import load_digits
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import plotly.express as px

digits = load_digits()

In [ ]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [ ]:
digits.feature_names

['pixel_0_0',
 'pixel_0_1',
 'pixel_0_2',
 'pixel_0_3',
 'pixel_0_4',
 'pixel_0_5',
 'pixel_0_6',
 'pixel_0_7',
 'pixel_1_0',
 'pixel_1_1',
 'pixel_1_2',
 'pixel_1_3',
 'pixel_1_4',
 'pixel_1_5',
 'pixel_1_6',
 'pixel_1_7',
 'pixel_2_0',
 'pixel_2_1',
 'pixel_2_2',
 'pixel_2_3',
 'pixel_2_4',
 'pixel_2_5',
 'pixel_2_6',
 'pixel_2_7',
 'pixel_3_0',
 'pixel_3_1',
 'pixel_3_2',
 'pixel_3_3',
 'pixel_3_4',
 'pixel_3_5',
 'pixel_3_6',
 'pixel_3_7',
 'pixel_4_0',
 'pixel_4_1',
 'pixel_4_2',
 'pixel_4_3',
 'pixel_4_4',
 'pixel_4_5',
 'pixel_4_6',
 'pixel_4_7',
 'pixel_5_0',
 'pixel_5_1',
 'pixel_5_2',
 'pixel_5_3',
 'pixel_5_4',
 'pixel_5_5',
 'pixel_5_6',
 'pixel_5_7',
 'pixel_6_0',
 'pixel_6_1',
 'pixel_6_2',
 'pixel_6_3',
 'pixel_6_4',
 'pixel_6_5',
 'pixel_6_6',
 'pixel_6_7',
 'pixel_7_0',
 'pixel_7_1',
 'pixel_7_2',
 'pixel_7_3',
 'pixel_7_4',
 'pixel_7_5',
 'pixel_7_6',
 'pixel_7_7']

In [ ]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [33]:
images = digits.images
labels = digits.target

In [29]:
images.ndim

In [34]:
images_flat = images.reshape((images.shape[0], -1)) # change to to dimantion

In [41]:
images_flat.ndim

2

In [35]:
df = pd.DataFrame(images_flat , columns=[f"pixel_{i}" for i in range(images_flat.shape[1])])
df["digit"] = labels.astype("str")

In [36]:
df

pixel_0  pixel_1  pixel_2  pixel_3  pixel_4  pixel_5  pixel_6  pixel_7  \
0         0.0      0.0      5.0     13.0      9.0      1.0      0.0      0.0   
1         0.0      0.0      0.0     12.0     13.0      5.0      0.0      0.0   
2         0.0      0.0      0.0      4.0     15.0     12.0      0.0      0.0   
3         0.0      0.0      7.0     15.0     13.0      1.0      0.0      0.0   
4         0.0      0.0      0.0      1.0     11.0      0.0      0.0      0.0   
...       ...      ...      ...      ...      ...      ...      ...      ...   
1792      0.0      0.0      4.0     10.0     13.0      6.0      0.0      0.0   
1793      0.0      0.0      6.0     16.0     13.0     11.0      1.0      0.0   
1794      0.0      0.0      1.0     11.0     15.0      1.0      0.0      0.0   
1795      0.0      0.0      2.0     10.0      7.0      0.0      0.0      0.0   
1796      0.0      0.0     10.0     14.0      8.0      1.0      0.0      0.0   

      pixel_8  pixel_9  ...  pixel_55  pixel_56  pixel_57  pixel_58  pixel_59  \
0         0.0      0.0  ...       0.0       0.0       0.0       6.0      13.0   
1         0.0      0.0  ...       0.0       0.0       0.0       0.0      11.0   
2         0.0      0.0  ...       0.0       0.0       0.0       0.0       3.0   
3         0.0      8.0  ...       0.0       0.0       0.0       7.0      13.0   
4         0.0      0.0  ...       0.0       0.0       0.0       0.0       2.0   
...       ...      ...  ...       ...       ...       ...       ...       ...   
1792      0.0      1.0  ...       0.0       0.0       0.0       2.0      14.0   
1793      0.0      0.0  ...       0.0       0.0       0.0       6.0      16.0   
1794      0.0      0.0  ...       0.0       0.0       0.0       2.0       9.0   
1795      0.0      0.0  ...       0.0       0.0       0.0       5.0      12.0   
1796      0.0      2.0  ...       0.0       0.0       1.0       8.0      12.0   

      pixel_60  pixel_61  pixel_62  pixel_63  digit  
0         10.0       0.0       0.0       0.0      0  
1         16.0      10.0       0.0       0.0      1  
2         11.0      16.0       9.0       0.0      2  
3         13.0       9.0       0.0       0.0      3  
4         16.0       4.0       0.0       0.0      4  
...        ...       ...       ...       ...    ...  
1792      15.0       9.0       0.0       0.0      9  
1793      14.0       6.0       0.0       0.0      0  
1794      13.0       6.0       0.0       0.0      8  
1795      16.0      12.0       0.0       0.0      9  
1796      14.0      12.0       1.0       0.0      8  

[1797 rows x 65 columns]

In [44]:
fig =px.scatter(df,x = df.columns[:-1], color = "digit",title = "visulization of digits dataset")
fig.update_layout(showlegend = True,
                  xaxis_title = "pixles")
fig.show()

In [47]:
x = df.drop("digit", axis = 1)
y = df.digit

In [48]:
x ,y

(      pixel_0  pixel_1  pixel_2  pixel_3  pixel_4  pixel_5  pixel_6  pixel_7  \
 0         0.0      0.0      5.0     13.0      9.0      1.0      0.0      0.0   
 1         0.0      0.0      0.0     12.0     13.0      5.0      0.0      0.0   
 2         0.0      0.0      0.0      4.0     15.0     12.0      0.0      0.0   
 3         0.0      0.0      7.0     15.0     13.0      1.0      0.0      0.0   
 4         0.0      0.0      0.0      1.0     11.0      0.0      0.0      0.0   
 ...       ...      ...      ...      ...      ...      ...      ...      ...   
 1792      0.0      0.0      4.0     10.0     13.0      6.0      0.0      0.0   
 1793      0.0      0.0      6.0     16.0     13.0     11.0      1.0      0.0   
 1794      0.0      0.0      1.0     11.0     15.0      1.0      0.0      0.0   
 1795      0.0      0.0      2.0     10.0      7.0      0.0      0.0      0.0   
 1796      0.0      0.0     10.0     14.0      8.0      1.0      0.0      0.0   
 
       pixel_8  pixel_9  .

In [51]:
import plotly.graph_objects as go
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_digits

k_range = range(1, 21)
mean_accuracies = []

for k in k_range:
    model = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(model, x, y, cv=5, scoring='accuracy')
    mean_accuracies.append(scores.mean())


fig = go.Figure()

fig.add_trace(go.Scatter(x=list(k_range), y=mean_accuracies, mode='lines+markers', name='Mean Cross-Validation Accuracy'))

fig.update_layout(
    title='k-NN Varying number of neighbors',
    xaxis_title='Number of Neighbors K',
    yaxis_title='Mean Cross-Validation Accuracy',
    xaxis=dict(tickvals=list(k_range)),
    width=800,
    height=600,
    showlegend=True,
    template='plotly_white'
)


fig.show()


In [52]:
# know after we know the best value of k lets make the model
from sklearn.model_selection import train_test_split
xtrain , xtest ,ytain,ytest = train_test_split(x ,y , train_size=0.8 , random_state=2)

In [54]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=2)

In [56]:
knn_model.fit(xtrain,ytain)

KNeighborsClassifier(n_neighbors=2)

In [57]:
knn_model.score(xtest,ytest) # good score

0.9861111111111112

In [58]:
pred = knn_model.predict(xtest)
pred

array(['4', '0', '9', '1', '7', '7', '1', '5', '1', '6', '6', '7', '6',
       '1', '5', '5', '7', '6', '2', '7', '4', '6', '4', '1', '5', '2',
       '9', '5', '4', '6', '5', '6', '3', '4', '0', '9', '9', '8', '4',
       '6', '8', '8', '5', '7', '9', '6', '9', '6', '1', '3', '0', '1',
       '9', '7', '3', '3', '1', '1', '8', '8', '9', '8', '5', '4', '4',
       '7', '3', '5', '8', '4', '3', '1', '3', '8', '7', '3', '3', '0',
       '8', '7', '2', '8', '5', '3', '8', '7', '6', '4', '6', '2', '2',
       '0', '1', '1', '5', '3', '5', '7', '6', '8', '2', '2', '6', '4',
       '6', '7', '3', '7', '3', '9', '4', '7', '0', '3', '5', '1', '5',
       '0', '3', '9', '2', '7', '3', '2', '0', '8', '1', '9', '2', '1',
       '9', '1', '0', '3', '4', '3', '0', '7', '3', '2', '2', '7', '3',
       '1', '6', '7', '2', '8', '3', '1', '1', '6', '4', '8', '2', '1',
       '8', '4', '1', '3', '1', '1', '9', '5', '4', '8', '7', '4', '8',
       '9', '5', '7', '6', '9', '0', '0', '4', '0', '0', '4', '0

In [59]:
# visulization of the confution matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest ,pred)
cm

array([[32,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 44,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 31,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 36,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 33,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0, 43,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 35,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 40,  0,  0],
       [ 0,  1,  0,  1,  0,  0,  0,  0, 34,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  0, 27]])

In [66]:
fig = px.imshow(cm , labels = dict(x = "predicted", y = "actule"), x = [0,1,2,3,4,5,6,7,8,9],
                y = [0,1,2,3,4,5,6,7,8,9])
fig.update_layout(
    title_text = "confusion matrix",
    xaxis_title = "predicted labels", yaxis_title = "actule labels"
)
fig.show()

In [61]:
from sklearn.metrics import classification_report
print(classification_report(ytest, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       0.98      1.00      0.99        44
           2       1.00      1.00      1.00        31
           3       0.97      1.00      0.99        36
           4       1.00      0.94      0.97        35
           5       1.00      1.00      1.00        43
           6       1.00      1.00      1.00        35
           7       0.93      1.00      0.96        40
           8       1.00      0.94      0.97        36
           9       1.00      0.96      0.98        28

    accuracy                           0.99       360
   macro avg       0.99      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360



In [71]:
import plotly.figure_factory as ff
fig = ff.create_annotated_heatmap(z=cm,x = [0,1,2,3,4,5,6,7,8,9],y = [0,1,2,3,4,5,6,7,8,9], colorscale='Viridis')

# Update layout
fig.update_layout(
    title='Confusion Matrix',
    xaxis_title='Predicted labels',
    yaxis_title='actuel labels',
    width=600,
    height=400,
    )

# Show plot
fig.show()